server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: ai-code-master
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 123456

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.air.aicodemaster.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

